# Generated by Django 5.2.5 on 2025-10-01 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200316_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Movie_name', models.CharField(max_length=128)),
                ('Movie_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Movie_year', models.IntegerField()),
                ('Movie_genre', models.CharField()),
            ],
        ),
    ]
