# Generated by Django 5.2.6 on 2025-10-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course_Taken',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
