# Generated by Django 5.2.6 on 2025-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_course_taken_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Movie_genre',
            field=models.CharField(max_length=128),
        ),
    ]
